version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: nutriplanner
      POSTGRES_DB: nutriplanner
    ports:
      - 5433:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data